<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransactionInfo.proto

namespace GPBMetadata;

class TransactionInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
è
TransactionInfo.prototemplate"Ú
TransactionBody
nonce (
address (
	recipient (
amount (
fees (
inner_codetype (
	code_data (
ext_data (
	timestamp	 (
biz_code
 (
version (
chainId (

to ("[
TransactionInfo
hash (\'
body (2.template.TransactionBody
	signature (BZ./abi/test.protobproto3'
        , true);

        static::$is_initialized = true;
    }
}

