<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransactionInfo.proto

namespace Template;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>template.TransactionInfo</code>
 */
class TransactionInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     */
    protected $hash = '';
    /**
     * Generated from protobuf field <code>.template.TransactionBody body = 2;</code>
     */
    protected $body = null;
    /**
     * Generated from protobuf field <code>bytes signature = 3;</code>
     */
    protected $signature = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $hash
     *     @type \Template\TransactionBody $body
     *     @type string $signature
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TransactionInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Generated from protobuf field <code>bytes hash = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setHash($var)
    {
        GPBUtil::checkString($var, False);
        $this->hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.template.TransactionBody body = 2;</code>
     * @return \Template\TransactionBody|null
     */
    public function getBody()
    {
        return $this->body;
    }

    public function hasBody()
    {
        return isset($this->body);
    }

    public function clearBody()
    {
        unset($this->body);
    }

    /**
     * Generated from protobuf field <code>.template.TransactionBody body = 2;</code>
     * @param \Template\TransactionBody $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkMessage($var, \Template\TransactionBody::class);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 3;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

}

