<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransactionInfo.proto

namespace Template;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>template.TransactionBody</code>
 */
class TransactionBody extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 nonce = 1;</code>
     */
    protected $nonce = 0;
    /**
     * Generated from protobuf field <code>bytes address = 2;</code>
     */
    protected $address = '';
    /**
     *	repeated TransactionOutput outputs = 3;
     *
     * Generated from protobuf field <code>bytes recipient = 3;</code>
     */
    protected $recipient = '';
    /**
     * Generated from protobuf field <code>bytes amount = 4;</code>
     */
    protected $amount = '';
    /**
     *手续费高位
     *
     * Generated from protobuf field <code>bytes fees = 5;</code>
     */
    protected $fees = '';
    /**
     *内置指令交易[0=普通交易,1=多重签名交易(取消),2=类ETH交易，，3=RC721交易(取消)，4=XVM合约调用,5=JSVM合约调用(暂无),6=evfs交易,7=链委员会(暂无),8=链管理员组(暂无)
     *
     * Generated from protobuf field <code>int32 inner_codetype = 6;</code>
     */
    protected $inner_codetype = 0;
    /**
     *指令数据
     *
     * Generated from protobuf field <code>bytes code_data = 7;</code>
     */
    protected $code_data = '';
    /**
     * Generated from protobuf field <code>bytes ext_data = 8;</code>
     */
    protected $ext_data = '';
    /**
     * Generated from protobuf field <code>int64 timestamp = 9;</code>
     */
    protected $timestamp = 0;
    /**
     *业务代码
     *
     * Generated from protobuf field <code>bytes biz_code = 10;</code>
     */
    protected $biz_code = '';
    /**
     *版本
     *
     * Generated from protobuf field <code>bytes version = 11;</code>
     */
    protected $version = '';
    /**
     * Generated from protobuf field <code>int32 chainId = 12;</code>
     */
    protected $chainId = 0;
    /**
     * Generated from protobuf field <code>bytes to = 20;</code>
     */
    protected $to = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $nonce
     *     @type string $address
     *     @type string $recipient
     *          	repeated TransactionOutput outputs = 3;
     *     @type string $amount
     *     @type string $fees
     *          手续费高位
     *     @type int $inner_codetype
     *          内置指令交易[0=普通交易,1=多重签名交易(取消),2=类ETH交易，，3=RC721交易(取消)，4=XVM合约调用,5=JSVM合约调用(暂无),6=evfs交易,7=链委员会(暂无),8=链管理员组(暂无)
     *     @type string $code_data
     *          指令数据
     *     @type string $ext_data
     *     @type int|string $timestamp
     *     @type string $biz_code
     *          业务代码
     *     @type string $version
     *          版本
     *     @type int $chainId
     *     @type string $to
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\TransactionInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 nonce = 1;</code>
     * @return int|string
     */
    public function getNonce()
    {
        return $this->nonce;
    }

    /**
     * Generated from protobuf field <code>int64 nonce = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNonce($var)
    {
        GPBUtil::checkInt64($var);
        $this->nonce = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes address = 2;</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>bytes address = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->address = $var;

        return $this;
    }

    /**
     *	repeated TransactionOutput outputs = 3;
     *
     * Generated from protobuf field <code>bytes recipient = 3;</code>
     * @return string
     */
    public function getRecipient()
    {
        return $this->recipient;
    }

    /**
     *	repeated TransactionOutput outputs = 3;
     *
     * Generated from protobuf field <code>bytes recipient = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRecipient($var)
    {
        GPBUtil::checkString($var, False);
        $this->recipient = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes amount = 4;</code>
     * @return string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>bytes amount = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkString($var, False);
        $this->amount = $var;

        return $this;
    }

    /**
     *手续费高位
     *
     * Generated from protobuf field <code>bytes fees = 5;</code>
     * @return string
     */
    public function getFees()
    {
        return $this->fees;
    }

    /**
     *手续费高位
     *
     * Generated from protobuf field <code>bytes fees = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFees($var)
    {
        GPBUtil::checkString($var, False);
        $this->fees = $var;

        return $this;
    }

    /**
     *内置指令交易[0=普通交易,1=多重签名交易(取消),2=类ETH交易，，3=RC721交易(取消)，4=XVM合约调用,5=JSVM合约调用(暂无),6=evfs交易,7=链委员会(暂无),8=链管理员组(暂无)
     *
     * Generated from protobuf field <code>int32 inner_codetype = 6;</code>
     * @return int
     */
    public function getInnerCodetype()
    {
        return $this->inner_codetype;
    }

    /**
     *内置指令交易[0=普通交易,1=多重签名交易(取消),2=类ETH交易，，3=RC721交易(取消)，4=XVM合约调用,5=JSVM合约调用(暂无),6=evfs交易,7=链委员会(暂无),8=链管理员组(暂无)
     *
     * Generated from protobuf field <code>int32 inner_codetype = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setInnerCodetype($var)
    {
        GPBUtil::checkInt32($var);
        $this->inner_codetype = $var;

        return $this;
    }

    /**
     *指令数据
     *
     * Generated from protobuf field <code>bytes code_data = 7;</code>
     * @return string
     */
    public function getCodeData()
    {
        return $this->code_data;
    }

    /**
     *指令数据
     *
     * Generated from protobuf field <code>bytes code_data = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setCodeData($var)
    {
        GPBUtil::checkString($var, False);
        $this->code_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes ext_data = 8;</code>
     * @return string
     */
    public function getExtData()
    {
        return $this->ext_data;
    }

    /**
     * Generated from protobuf field <code>bytes ext_data = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setExtData($var)
    {
        GPBUtil::checkString($var, False);
        $this->ext_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 9;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>int64 timestamp = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     *业务代码
     *
     * Generated from protobuf field <code>bytes biz_code = 10;</code>
     * @return string
     */
    public function getBizCode()
    {
        return $this->biz_code;
    }

    /**
     *业务代码
     *
     * Generated from protobuf field <code>bytes biz_code = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setBizCode($var)
    {
        GPBUtil::checkString($var, False);
        $this->biz_code = $var;

        return $this;
    }

    /**
     *版本
     *
     * Generated from protobuf field <code>bytes version = 11;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *版本
     *
     * Generated from protobuf field <code>bytes version = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, False);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 chainId = 12;</code>
     * @return int
     */
    public function getChainId()
    {
        return $this->chainId;
    }

    /**
     * Generated from protobuf field <code>int32 chainId = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setChainId($var)
    {
        GPBUtil::checkInt32($var);
        $this->chainId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes to = 20;</code>
     * @return string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * Generated from protobuf field <code>bytes to = 20;</code>
     * @param string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, False);
        $this->to = $var;

        return $this;
    }

}

